package main

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	_ "github.com/mattn/go-sqlite3"
)

const createVideosTableSQL = `
CREATE TABLE IF NOT EXISTS videos (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	filename TEXT NOT NULL UNIQUE,
	path TEXT NOT NULL,
	quality TEXT,
	duration INTEGER,
	tags_json TEXT NOT NULL DEFAULT '[]',
	actors_json TEXT NOT NULL DEFAULT '[]',
	date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
	date_scanned DATETIME
);`

const createVideosTitleIndexSQL = `CREATE INDEX IF NOT EXISTS idx_videos_title ON videos(title);`

const createUsersTableSQL = `
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	force_password_change INTEGER NOT NULL DEFAULT 0
);`

const createSettingsTableSQL = `
CREATE TABLE IF NOT EXISTS settings (
	key TEXT PRIMARY KEY,
	value TEXT
);`

const createPlaylistsTableSQL = `
CREATE TABLE IF NOT EXISTS playlists (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE,
	description TEXT NOT NULL DEFAULT '',
	date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
	date_updated DATETIME DEFAULT CURRENT_TIMESTAMP
);`

const createPlaylistItemsTableSQL = `
CREATE TABLE IF NOT EXISTS playlist_items (
	playlist_id INTEGER NOT NULL,
	video_title TEXT NOT NULL,
	position INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (playlist_id, video_title),
	FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE
);`

const createPlaylistItemsPlaylistIndexSQL = `CREATE INDEX IF NOT EXISTS idx_playlist_items_playlist_id ON playlist_items(playlist_id, position);`

const createTorrentHistoryTableSQL = `
CREATE TABLE IF NOT EXISTS torrent_download_history (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	download_url TEXT NOT NULL,
	tracker TEXT NOT NULL,
	size INTEGER NOT NULL DEFAULT 0,
	seeders INTEGER NOT NULL DEFAULT 0,
	leechers INTEGER NOT NULL DEFAULT 0,
	freeleech INTEGER NOT NULL DEFAULT 0,
	status TEXT NOT NULL DEFAULT 'pending',
	downloaded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);`

const createTorrentHistoryDownloadedAtIndexSQL = `CREATE INDEX IF NOT EXISTS idx_torrent_history_downloaded_at ON torrent_download_history(downloaded_at DESC);`

const mediaPathSettingKey = "media_path"
const generateThumbnailsSettingKey = "generate_thumbnails"
const generateScrubberSpritesSettingKey = "generate_scrubber_sprites"
const generateHoverPreviewsSettingKey = "generate_hover_previews"
const autoGenerateDuringScanSettingKey = "auto_generate_during_scan"
const metadataTagsCatalogSettingKey = "metadata_tags_catalog"
const metadataActorsCatalogSettingKey = "metadata_actors_catalog"
const torrentIndexersSettingKey = "torrent_indexers"

type Store struct {
	db     *sql.DB
	logger *slog.Logger
}

func NewStore(dbPath string, logger *slog.Logger) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(dbPath), 0o755); err != nil {
		return nil, fmt.Errorf("create database directory: %w", err)
	}

	db, err := sql.Open("sqlite3", dbPath)
	if err != nil {
		return nil, fmt.Errorf("open database: %w", err)
	}

	db.SetMaxOpenConns(1)
	db.SetConnMaxLifetime(0)
	db.SetMaxIdleConns(1)

	store := &Store{db: db, logger: logger}
	if err := store.Init(); err != nil {
		_ = db.Close()
		return nil, err
	}

	return store, nil
}

func (s *Store) Init() error {
	if s.logger != nil {
		s.logger.Info("initializing database schema")
	}

	if _, err := s.db.Exec(`PRAGMA foreign_keys = ON`); err != nil {
		return fmt.Errorf("enable foreign keys: %w", err)
	}

	if _, err := s.db.Exec(createVideosTableSQL); err != nil {
		return fmt.Errorf("create videos table: %w", err)
	}
	if _, err := s.db.Exec(createVideosTitleIndexSQL); err != nil {
		return fmt.Errorf("create videos title index: %w", err)
	}
	if _, err := s.db.Exec(createUsersTableSQL); err != nil {
		return fmt.Errorf("create users table: %w", err)
	}
	if _, err := s.db.Exec(createSettingsTableSQL); err != nil {
		return fmt.Errorf("create settings table: %w", err)
	}
	if _, err := s.db.Exec(createPlaylistsTableSQL); err != nil {
		return fmt.Errorf("create playlists table: %w", err)
	}
	if _, err := s.db.Exec(createPlaylistItemsTableSQL); err != nil {
		return fmt.Errorf("create playlist items table: %w", err)
	}
	if _, err := s.db.Exec(createPlaylistItemsPlaylistIndexSQL); err != nil {
		return fmt.Errorf("create playlist items index: %w", err)
	}
	if _, err := s.db.Exec(createTorrentHistoryTableSQL); err != nil {
		return fmt.Errorf("create torrent history table: %w", err)
	}
	if _, err := s.db.Exec(createTorrentHistoryDownloadedAtIndexSQL); err != nil {
		return fmt.Errorf("create torrent history index: %w", err)
	}
	if _, err := s.db.Exec(`DELETE FROM settings WHERE key = 'hard_link_destination'`); err != nil {
		return fmt.Errorf("remove retired hardlink setting: %w", err)
	}

	if err := s.migrateTorrentHistoryStatus(); err != nil {
		return err
	}

	if err := s.migrateUserForcePasswordChange(); err != nil {
		return err
	}

	hasTitle, err := s.hasVideosColumn("title")
	if err != nil {
		return err
	}

	if !hasTitle {
		if _, err := s.db.Exec(`DROP TABLE IF EXISTS videos`); err != nil {
			return fmt.Errorf("drop old videos table: %w", err)
		}

		if _, err := s.db.Exec(createVideosTableSQL); err != nil {
			return fmt.Errorf("recreate videos table: %w", err)
		}
		if _, err := s.db.Exec(createVideosTitleIndexSQL); err != nil {
			return fmt.Errorf("recreate videos title index: %w", err)
		}

		if s.logger != nil {
			s.logger.Info("migrated videos table schema", "added_column", "title")
		}
	}

	hasQuality, err := s.hasVideosColumn("quality")
	if err != nil {
		return err
	}
	if !hasQuality {
		if _, err := s.db.Exec(`ALTER TABLE videos ADD COLUMN quality TEXT`); err != nil {
			return fmt.Errorf("add quality column: %w", err)
		}
		if s.logger != nil {
			s.logger.Info("migrated videos table schema", "added_column", "quality")
		}
	}

	hasTags, err := s.hasVideosColumn("tags_json")
	if err != nil {
		return err
	}
	if !hasTags {
		if _, err := s.db.Exec(`ALTER TABLE videos ADD COLUMN tags_json TEXT NOT NULL DEFAULT '[]'`); err != nil {
			return fmt.Errorf("add tags_json column: %w", err)
		}
		if s.logger != nil {
			s.logger.Info("migrated videos table schema", "added_column", "tags_json")
		}
	}

	hasActors, err := s.hasVideosColumn("actors_json")
	if err != nil {
		return err
	}
	if !hasActors {
		if _, err := s.db.Exec(`ALTER TABLE videos ADD COLUMN actors_json TEXT NOT NULL DEFAULT '[]'`); err != nil {
			return fmt.Errorf("add actors_json column: %w", err)
		}
		if s.logger != nil {
			s.logger.Info("migrated videos table schema", "added_column", "actors_json")
		}
	}

	return nil
}

func (s *Store) GetUserByUsername(username string) (User, error) {
	var user User
	var forceChange int
	err := s.db.QueryRow(`SELECT id, username, password_hash, force_password_change FROM users WHERE username = ?`, username).Scan(&user.ID, &user.Username, &user.Password, &forceChange)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return User{}, err
		}
		return User{}, fmt.Errorf("get user by username: %w", err)
	}
	user.ForcePasswordChange = forceChange != 0

	return user, nil
}

func (s *Store) UpdatePassword(username string, newHash string) error {
	result, err := s.db.Exec(`UPDATE users SET password_hash = ?, force_password_change = 0 WHERE username = ?`, newHash, username)
	if err != nil {
		return fmt.Errorf("update password: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("read updated rows: %w", err)
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (s *Store) CreateDefaultUser() error {
	var count int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM users`).Scan(&count); err != nil {
		return fmt.Errorf("count users: %w", err)
	}
	if count > 0 {
		return nil
	}

	hash, err := hashPassword("admin")
	if err != nil {
		return fmt.Errorf("hash default password: %w", err)
	}

	if _, err := s.db.Exec(`INSERT INTO users (username, password_hash, force_password_change) VALUES (?, ?, 1)`, "admin", hash); err != nil {
		return fmt.Errorf("create default user: %w", err)
	}

	if s.logger != nil {
		s.logger.Info("created default user", "username", "admin")
	}

	return nil
}

func (s *Store) GetSetting(key string) (string, error) {
	var value string
	if err := s.db.QueryRow(`SELECT value FROM settings WHERE key = ?`, key).Scan(&value); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return "", err
		}
		return "", fmt.Errorf("get setting: %w", err)
	}

	return value, nil
}

func (s *Store) SetSetting(key, value string) error {
	_, err := s.db.Exec(`
		INSERT INTO settings (key, value)
		VALUES (?, ?)
		ON CONFLICT(key) DO UPDATE SET value = excluded.value`, key, value)
	if err != nil {
		return fmt.Errorf("set setting: %w", err)
	}

	return nil
}

func (s *Store) GetMediaPath() (string, error) {
	return s.GetSetting(mediaPathSettingKey)
}

func (s *Store) SetMediaPath(path string) error {
	return s.SetSetting(mediaPathSettingKey, path)
}

func (s *Store) GetGenerationSettings() (GenerationSettingsResponse, error) {
	var settings GenerationSettingsResponse

	thumbnailsValue, err := s.GetSetting(generateThumbnailsSettingKey)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return settings, err
	}
	settings.GenerateThumbnails = thumbnailsValue == "true"

	scrubberValue, err := s.GetSetting(generateScrubberSpritesSettingKey)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return settings, err
	}
	settings.GenerateScrubberSprites = scrubberValue == "true"

	hoverValue, err := s.GetSetting(generateHoverPreviewsSettingKey)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return settings, err
	}
	settings.GenerateHoverPreviews = hoverValue == "true"

	autoValue, err := s.GetSetting(autoGenerateDuringScanSettingKey)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return settings, err
	}
	settings.AutoGenerateDuringScan = autoValue == "true"

	return settings, nil
}

func (s *Store) SetGenerationSettings(settings GenerationSettingsRequest) error {
	if err := s.SetSetting(generateThumbnailsSettingKey, strconv.FormatBool(settings.GenerateThumbnails)); err != nil {
		return err
	}
	if err := s.SetSetting(generateScrubberSpritesSettingKey, strconv.FormatBool(settings.GenerateScrubberSprites)); err != nil {
		return err
	}
	if err := s.SetSetting(generateHoverPreviewsSettingKey, strconv.FormatBool(settings.GenerateHoverPreviews)); err != nil {
		return err
	}
	if err := s.SetSetting(autoGenerateDuringScanSettingKey, strconv.FormatBool(settings.AutoGenerateDuringScan)); err != nil {
		return err
	}
	return nil
}

func (s *Store) ClearDatabase() error {
	if _, err := s.db.Exec(`DROP TABLE IF EXISTS playlist_items`); err != nil {
		return fmt.Errorf("drop playlist items table: %w", err)
	}
	if _, err := s.db.Exec(`DROP TABLE IF EXISTS playlists`); err != nil {
		return fmt.Errorf("drop playlists table: %w", err)
	}
	if _, err := s.db.Exec(`DROP TABLE IF EXISTS videos`); err != nil {
		return fmt.Errorf("drop videos table: %w", err)
	}
	if _, err := s.db.Exec(`DROP INDEX IF EXISTS idx_videos_title`); err != nil {
		return fmt.Errorf("drop videos index: %w", err)
	}
	if err := s.Init(); err != nil {
		return fmt.Errorf("reinitialize database: %w", err)
	}
	if s.logger != nil {
		s.logger.Info("database cleared successfully")
	}
	return nil
}

func (s *Store) hasVideosColumn(name string) (bool, error) {
	var count int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM pragma_table_info('videos') WHERE name = ?`, name).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("check videos schema: %w", err)
	}

	return count > 0, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}

func (s *Store) ListVideos() ([]Video, error) {
	rows, err := s.db.Query(`
		SELECT id, title, filename, path, quality, duration, tags_json, actors_json, date_added, date_scanned
		FROM videos
		ORDER BY date_added DESC, id DESC`)
	if err != nil {
		return nil, fmt.Errorf("query videos: %w", err)
	}
	defer rows.Close()

	var videos []Video
	for rows.Next() {
		video, err := scanVideoSummary(rows)
		if err != nil {
			return nil, fmt.Errorf("scan video summary: %w", err)
		}
		videos = append(videos, video)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate videos: %w", err)
	}

	return videos, nil
}

func (s *Store) GetVideoByID(id int64) (Video, error) {
	row := s.db.QueryRow(`
		SELECT id, title, filename, path, quality, duration, tags_json, actors_json, date_added, date_scanned
		FROM videos
		WHERE id = ?`, id)

	video, err := scanVideoDetail(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Video{}, err
		}
		return Video{}, fmt.Errorf("get video by id: %w", err)
	}

	return video, nil
}

func (s *Store) GetVideoByPath(path string) (Video, error) {
	row := s.db.QueryRow(`
		SELECT id, title, filename, path, quality, duration, tags_json, actors_json, date_added, date_scanned
		FROM videos
		WHERE path = ?`, path)

	video, err := scanVideoDetail(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Video{}, err
		}
		return Video{}, fmt.Errorf("get video by path: %w", err)
	}

	return video, nil
}

func (s *Store) InsertVideo(video ScannedVideo) error {
	metadataTagsJSON := "[]"
	metadataActorsJSON := "[]"
	if existingTagsJSON, existingActorsJSON, err := s.getMetadataByTitle(video.Title); err == nil {
		metadataTagsJSON = existingTagsJSON
		metadataActorsJSON = existingActorsJSON
	} else if !errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("load existing group metadata: %w", err)
	}

	_, err := s.db.Exec(`
		INSERT INTO videos (title, filename, path, quality, duration, tags_json, actors_json, date_scanned)
		VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`,
		video.Title, video.Filename, video.Path, video.Quality, video.Duration, metadataTagsJSON, metadataActorsJSON,
	)
	if err != nil {
		return fmt.Errorf("insert video: %w", err)
	}
	if s.logger != nil {
		s.logger.Info("video inserted", "title", video.Title, "filename", video.Filename)
	}
	return nil
}

func (s *Store) UpdateVideoMetadata(id int64, video ScannedVideo) error {
	_, err := s.db.Exec(`
		UPDATE videos
		SET title = ?, filename = ?, quality = ?, duration = ?, date_scanned = CURRENT_TIMESTAMP
		WHERE id = ?`,
		video.Title, video.Filename, video.Quality, video.Duration, id,
	)
	if err != nil {
		return fmt.Errorf("update video metadata: %w", err)
	}
	if s.logger != nil {
		s.logger.Info("video metadata updated", "video_id", id, "title", video.Title, "filename", video.Filename)
	}
	return nil
}

func (s *Store) UpdateVideoGroupMetadata(id int64, tags []string, actors []string) error {
	var title string
	if err := s.db.QueryRow(`SELECT title FROM videos WHERE id = ?`, id).Scan(&title); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return err
		}
		return fmt.Errorf("load video title for metadata update: %w", err)
	}

	tagsJSON, err := marshalStringList(tags)
	if err != nil {
		return fmt.Errorf("encode tags: %w", err)
	}
	actorsJSON, err := marshalStringList(actors)
	if err != nil {
		return fmt.Errorf("encode actors: %w", err)
	}

	_, err = s.db.Exec(`
		UPDATE videos
		SET tags_json = ?, actors_json = ?
		WHERE title = ?`, tagsJSON, actorsJSON, title)
	if err != nil {
		return fmt.Errorf("update video group metadata: %w", err)
	}

	if s.logger != nil {
		s.logger.Info("video group metadata updated", "video_id", id, "title", title, "tags_count", len(tags), "actors_count", len(actors))
	}

	return nil
}

func (s *Store) BulkUpdateVideoGroupsMetadata(ids []int64, addTags []string, removeTags []string, addActors []string, removeActors []string) ([]VideoGroup, error) {
	cleanIDs := uniqueInt64s(ids)
	if len(cleanIDs) == 0 {
		return nil, sql.ErrNoRows
	}

	titles, err := s.getTitlesForVideoIDs(cleanIDs)
	if err != nil {
		return nil, err
	}
	if len(titles) == 0 {
		return nil, sql.ErrNoRows
	}

	addTags = sanitizeStringList(addTags)
	removeTags = sanitizeStringList(removeTags)
	addActors = sanitizeStringList(addActors)
	removeActors = sanitizeStringList(removeActors)

	tx, err := s.db.Begin()
	if err != nil {
		return nil, fmt.Errorf("begin bulk metadata update: %w", err)
	}

	updatedTitles := make([]string, 0, len(titles))
	for _, title := range titles {
		tags, actors, err := loadMetadataForTitle(tx, title)
		if err != nil {
			_ = tx.Rollback()
			return nil, err
		}

		nextTags := applyStringListChanges(tags, addTags, removeTags)
		nextActors := applyStringListChanges(actors, addActors, removeActors)

		tagsJSON, err := marshalStringList(nextTags)
		if err != nil {
			_ = tx.Rollback()
			return nil, fmt.Errorf("encode bulk tags: %w", err)
		}
		actorsJSON, err := marshalStringList(nextActors)
		if err != nil {
			_ = tx.Rollback()
			return nil, fmt.Errorf("encode bulk actors: %w", err)
		}

		if _, err := tx.Exec(`
			UPDATE videos
			SET tags_json = ?, actors_json = ?
			WHERE title = ?`, tagsJSON, actorsJSON, title); err != nil {
			_ = tx.Rollback()
			return nil, fmt.Errorf("bulk update video group metadata: %w", err)
		}

		updatedTitles = append(updatedTitles, title)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit bulk metadata update: %w", err)
	}

	updatedGroups := make([]VideoGroup, 0, len(updatedTitles))
	for _, title := range updatedTitles {
		group, err := s.GetVideoGroupByTitle(title)
		if err != nil {
			return nil, err
		}
		updatedGroups = append(updatedGroups, group)
	}

	if s.logger != nil {
		s.logger.Info("bulk video metadata updated", "group_count", len(updatedGroups), "tags_added", len(addTags), "tags_removed", len(removeTags), "actors_added", len(addActors), "actors_removed", len(removeActors))
	}

	return updatedGroups, nil
}

func (s *Store) ListMetadataOptions() (VideoMetadataOptionsResponse, error) {
	groups, err := s.ListVideoGroups()
	if err != nil {
		return VideoMetadataOptionsResponse{}, err
	}

	tagsCatalog, actorsCatalog, err := s.GetMetadataCatalog()
	if err != nil {
		return VideoMetadataOptionsResponse{}, err
	}

	tagSet := map[string]string{}
	actorSet := map[string]string{}
	collectCaseInsensitiveStrings(tagSet, tagsCatalog)
	collectCaseInsensitiveStrings(actorSet, actorsCatalog)
	for _, group := range groups {
		collectCaseInsensitiveStrings(tagSet, group.Tags)
		collectCaseInsensitiveStrings(actorSet, group.Actors)
	}

	return VideoMetadataOptionsResponse{
		Tags:   sortedStringMapValues(tagSet),
		Actors: sortedStringMapValues(actorSet),
	}, nil
}

func (s *Store) GetMetadataCatalog() ([]string, []string, error) {
	tagsValue, err := s.GetSetting(metadataTagsCatalogSettingKey)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return nil, nil, fmt.Errorf("get metadata tags catalog: %w", err)
	}
	actorsValue, err := s.GetSetting(metadataActorsCatalogSettingKey)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return nil, nil, fmt.Errorf("get metadata actors catalog: %w", err)
	}

	return parseStringList(tagsValue), parseStringList(actorsValue), nil
}

func (s *Store) ListMetadataCatalog() (VideoMetadataOptionsResponse, error) {
	tags, actors, err := s.GetMetadataCatalog()
	if err != nil {
		return VideoMetadataOptionsResponse{}, err
	}

	return VideoMetadataOptionsResponse{
		Tags:   tags,
		Actors: actors,
	}, nil
}

func (s *Store) UpdateMetadataCatalog(addTags []string, removeTags []string, addActors []string, removeActors []string) (VideoMetadataOptionsResponse, error) {
	addTags = sanitizeStringList(addTags)
	removeTags = sanitizeStringList(removeTags)
	addActors = sanitizeStringList(addActors)
	removeActors = sanitizeStringList(removeActors)

	tx, err := s.db.Begin()
	if err != nil {
		return VideoMetadataOptionsResponse{}, fmt.Errorf("begin metadata catalog update: %w", err)
	}

	tagsCatalog, actorsCatalog, err := s.getMetadataCatalogTx(tx)
	if err != nil {
		_ = tx.Rollback()
		return VideoMetadataOptionsResponse{}, err
	}

	nextTagsCatalog := applyStringListChanges(tagsCatalog, addTags, removeTags)
	nextActorsCatalog := applyStringListChanges(actorsCatalog, addActors, removeActors)

	if err := s.setMetadataCatalogTx(tx, nextTagsCatalog, nextActorsCatalog); err != nil {
		_ = tx.Rollback()
		return VideoMetadataOptionsResponse{}, err
	}

	if len(removeTags) > 0 || len(removeActors) > 0 {
		if err := removeMetadataValuesFromAllVideosTx(tx, removeTags, removeActors); err != nil {
			_ = tx.Rollback()
			return VideoMetadataOptionsResponse{}, err
		}
	}

	if err := tx.Commit(); err != nil {
		return VideoMetadataOptionsResponse{}, fmt.Errorf("commit metadata catalog update: %w", err)
	}

	if s.logger != nil {
		s.logger.Info("metadata catalog updated", "tags_added", len(addTags), "tags_removed", len(removeTags), "actors_added", len(addActors), "actors_removed", len(removeActors))
	}

	return s.ListMetadataOptions()
}

func (s *Store) ListTorrentIndexers() ([]TorrentIndexer, error) {
	value, err := s.GetSetting(torrentIndexersSettingKey)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return []TorrentIndexer{}, nil
		}
		return nil, fmt.Errorf("get torrent indexers: %w", err)
	}

	return parseTorrentIndexers(value)
}

func (s *Store) SaveTorrentIndexers(indexers []TorrentIndexer) error {
	encoded, err := marshalTorrentIndexers(indexers)
	if err != nil {
		return err
	}
	if err := s.SetSetting(torrentIndexersSettingKey, encoded); err != nil {
		return fmt.Errorf("save torrent indexers: %w", err)
	}
	return nil
}

func (s *Store) AddTorrentIndexer(indexer TorrentIndexer) ([]TorrentIndexer, error) {
	tx, err := s.db.Begin()
	if err != nil {
		return nil, fmt.Errorf("begin add torrent indexer: %w", err)
	}

	indexers, err := s.listTorrentIndexersTx(tx)
	if err != nil {
		_ = tx.Rollback()
		return nil, err
	}

	normalizedURL := strings.TrimSpace(indexer.TorznabURL)
	normalizedKey := strings.TrimSpace(indexer.APIKey)
	for _, existing := range indexers {
		if strings.EqualFold(strings.TrimSpace(existing.TorznabURL), normalizedURL) && strings.TrimSpace(existing.APIKey) == normalizedKey {
			_ = tx.Rollback()
			return nil, errors.New("indexer already exists")
		}
	}

	indexers = append(indexers, sanitizeTorrentIndexer(indexer))
	if err := s.saveTorrentIndexersTx(tx, indexers); err != nil {
		_ = tx.Rollback()
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit add torrent indexer: %w", err)
	}

	if s.logger != nil {
		s.logger.Info("torrent indexer added", "tracker", indexer.Tracker)
	}

	return indexers, nil
}

func (s *Store) DeleteTorrentIndexer(id string) ([]TorrentIndexer, error) {
	tx, err := s.db.Begin()
	if err != nil {
		return nil, fmt.Errorf("begin delete torrent indexer: %w", err)
	}

	indexers, err := s.listTorrentIndexersTx(tx)
	if err != nil {
		_ = tx.Rollback()
		return nil, err
	}

	filtered := make([]TorrentIndexer, 0, len(indexers))
	removed := false
	for _, indexer := range indexers {
		if indexer.ID == id {
			removed = true
			continue
		}
		filtered = append(filtered, indexer)
	}
	if !removed {
		_ = tx.Rollback()
		return nil, sql.ErrNoRows
	}

	if err := s.saveTorrentIndexersTx(tx, filtered); err != nil {
		_ = tx.Rollback()
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit delete torrent indexer: %w", err)
	}

	if s.logger != nil {
		s.logger.Info("torrent indexer removed", "indexer_id", id)
	}

	return filtered, nil
}

func (s *Store) listTorrentIndexersTx(tx *sql.Tx) ([]TorrentIndexer, error) {
	value, err := getOptionalSettingTx(tx, torrentIndexersSettingKey)
	if err != nil {
		return nil, fmt.Errorf("get torrent indexers in tx: %w", err)
	}

	return parseTorrentIndexers(value)
}

func (s *Store) saveTorrentIndexersTx(tx *sql.Tx, indexers []TorrentIndexer) error {
	encoded, err := marshalTorrentIndexers(indexers)
	if err != nil {
		return err
	}
	if err := setSettingTx(tx, torrentIndexersSettingKey, encoded); err != nil {
		return fmt.Errorf("save torrent indexers in tx: %w", err)
	}
	return nil
}

func (s *Store) ListPlaylists() ([]PlaylistSummary, error) {
	if err := s.pruneStalePlaylistItems(); err != nil {
		return nil, err
	}

	rows, err := s.db.Query(`
		SELECT p.id, p.name, p.description, COUNT(vt.title) AS item_count, p.date_created, p.date_updated
		FROM playlists p
		LEFT JOIN playlist_items pi ON pi.playlist_id = p.id
		LEFT JOIN (SELECT DISTINCT title FROM videos) vt ON vt.title = pi.video_title
		GROUP BY p.id, p.name, p.description, p.date_created, p.date_updated
		ORDER BY LOWER(p.name), p.id`)
	if err != nil {
		return nil, fmt.Errorf("query playlists: %w", err)
	}
	defer rows.Close()

	playlists := make([]PlaylistSummary, 0)
	for rows.Next() {
		playlist, err := scanPlaylistSummary(rows)
		if err != nil {
			return nil, fmt.Errorf("scan playlist summary: %w", err)
		}
		playlists = append(playlists, playlist)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate playlists: %w", err)
	}

	return playlists, nil
}

func (s *Store) GetPlaylistByID(id int64) (Playlist, error) {
	if err := s.pruneStalePlaylistItemsForPlaylist(id); err != nil && !errors.Is(err, sql.ErrNoRows) {
		return Playlist{}, err
	}

	var playlist Playlist
	var dateCreated sql.NullTime
	var dateUpdated sql.NullTime
	err := s.db.QueryRow(`
		SELECT id, name, description, date_created, date_updated
		FROM playlists
		WHERE id = ?`, id).Scan(&playlist.ID, &playlist.Name, &playlist.Description, &dateCreated, &dateUpdated)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Playlist{}, err
		}
		return Playlist{}, fmt.Errorf("get playlist by id: %w", err)
	}

	assignPlaylistTimes(&playlist, dateCreated, dateUpdated)
	items, err := s.listPlaylistItems(id)
	if err != nil {
		return Playlist{}, err
	}
	playlist.Items = items

	return playlist, nil
}

func (s *Store) CreatePlaylist(name string, description string, videoIDs []int64) (Playlist, error) {
	name = strings.TrimSpace(name)
	description = strings.TrimSpace(description)
	if name == "" {
		return Playlist{}, errors.New("playlist name is required")
	}

	titles, err := s.getTitlesForVideoIDsOrdered(videoIDs)
	if err != nil {
		return Playlist{}, err
	}

	tx, err := s.db.Begin()
	if err != nil {
		return Playlist{}, fmt.Errorf("begin create playlist: %w", err)
	}

	result, err := tx.Exec(`INSERT INTO playlists (name, description) VALUES (?, ?)`, name, description)
	if err != nil {
		_ = tx.Rollback()
		return Playlist{}, fmt.Errorf("create playlist: %w", err)
	}

	playlistID, err := result.LastInsertId()
	if err != nil {
		_ = tx.Rollback()
		return Playlist{}, fmt.Errorf("read created playlist id: %w", err)
	}

	if err := setPlaylistTitlesTx(tx, playlistID, titles); err != nil {
		_ = tx.Rollback()
		return Playlist{}, err
	}

	if err := tx.Commit(); err != nil {
		return Playlist{}, fmt.Errorf("commit create playlist: %w", err)
	}

	return s.GetPlaylistByID(playlistID)
}

func (s *Store) UpdatePlaylist(id int64, name string, description string) (Playlist, error) {
	name = strings.TrimSpace(name)
	description = strings.TrimSpace(description)
	if name == "" {
		return Playlist{}, errors.New("playlist name is required")
	}

	result, err := s.db.Exec(`
		UPDATE playlists
		SET name = ?, description = ?, date_updated = CURRENT_TIMESTAMP
		WHERE id = ?`, name, description, id)
	if err != nil {
		return Playlist{}, fmt.Errorf("update playlist: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return Playlist{}, fmt.Errorf("read updated playlist rows: %w", err)
	}
	if rowsAffected == 0 {
		return Playlist{}, sql.ErrNoRows
	}

	return s.GetPlaylistByID(id)
}

func (s *Store) DeletePlaylist(id int64) error {
	result, err := s.db.Exec(`DELETE FROM playlists WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("delete playlist: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("read deleted playlist rows: %w", err)
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}

	return nil
}

func (s *Store) AddPlaylistItems(id int64, videoIDs []int64) (Playlist, error) {
	titlesToAdd, err := s.getTitlesForVideoIDsOrdered(videoIDs)
	if err != nil {
		return Playlist{}, err
	}

	existingTitles, err := s.getPlaylistTitles(id)
	if err != nil {
		return Playlist{}, err
	}

	combined := append(append([]string(nil), existingTitles...), titlesToAdd...)
	combined = uniqueStringsPreserveOrder(combined)
	if err := s.replacePlaylistTitles(id, combined); err != nil {
		return Playlist{}, err
	}

	return s.GetPlaylistByID(id)
}

func (s *Store) ReplacePlaylistItems(id int64, videoIDs []int64) (Playlist, error) {
	titles, err := s.getTitlesForVideoIDsOrdered(videoIDs)
	if err != nil {
		return Playlist{}, err
	}

	if err := s.replacePlaylistTitles(id, titles); err != nil {
		return Playlist{}, err
	}

	return s.GetPlaylistByID(id)
}

func (s *Store) RemovePlaylistItem(id int64, videoID int64) (Playlist, error) {
	title, err := s.getTitleForVideoID(videoID)
	if err != nil {
		return Playlist{}, err
	}

	existingTitles, err := s.getPlaylistTitles(id)
	if err != nil {
		return Playlist{}, err
	}

	filtered := make([]string, 0, len(existingTitles))
	for _, existingTitle := range existingTitles {
		if existingTitle == title {
			continue
		}
		filtered = append(filtered, existingTitle)
	}

	if len(filtered) == len(existingTitles) {
		return Playlist{}, sql.ErrNoRows
	}

	if err := s.replacePlaylistTitles(id, filtered); err != nil {
		return Playlist{}, err
	}

	return s.GetPlaylistByID(id)
}

func (s *Store) IsUniqueFilenameError(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), "UNIQUE constraint failed: videos.filename")
}

func (s *Store) IsUniquePlaylistNameError(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), "UNIQUE constraint failed: playlists.name")
}

func scanVideoSummary(scanner interface{ Scan(dest ...any) error }) (Video, error) {
	var video Video
	var dateAdded sql.NullTime
	var dateScanned sql.NullTime
	var quality sql.NullString
	var tagsJSON string
	var actorsJSON string

	if err := scanner.Scan(&video.ID, &video.Title, &video.Filename, &video.Path, &quality, &video.Duration, &tagsJSON, &actorsJSON, &dateAdded, &dateScanned); err != nil {
		return Video{}, err
	}

	if quality.Valid {
		video.Quality = quality.String
	}
	video.Tags = parseStringList(tagsJSON)
	video.Actors = parseStringList(actorsJSON)

	assignVideoTimes(&video, dateAdded, dateScanned)
	return video, nil
}

func scanVideoDetail(scanner interface{ Scan(dest ...any) error }) (Video, error) {
	var video Video
	var dateAdded sql.NullTime
	var dateScanned sql.NullTime
	var quality sql.NullString
	var tagsJSON string
	var actorsJSON string

	if err := scanner.Scan(&video.ID, &video.Title, &video.Filename, &video.Path, &quality, &video.Duration, &tagsJSON, &actorsJSON, &dateAdded, &dateScanned); err != nil {
		return Video{}, err
	}

	if quality.Valid {
		video.Quality = quality.String
	}
	video.Tags = parseStringList(tagsJSON)
	video.Actors = parseStringList(actorsJSON)

	assignVideoTimes(&video, dateAdded, dateScanned)
	return video, nil
}

func scanPlaylistSummary(scanner interface{ Scan(dest ...any) error }) (PlaylistSummary, error) {
	var playlist PlaylistSummary
	var dateCreated sql.NullTime
	var dateUpdated sql.NullTime

	if err := scanner.Scan(&playlist.ID, &playlist.Name, &playlist.Description, &playlist.ItemCount, &dateCreated, &dateUpdated); err != nil {
		return PlaylistSummary{}, err
	}

	assignPlaylistSummaryTimes(&playlist, dateCreated, dateUpdated)
	return playlist, nil
}

func assignVideoTimes(video *Video, dateAdded, dateScanned sql.NullTime) {
	if dateAdded.Valid {
		t := dateAdded.Time.UTC()
		video.DateAdded = &t
	}
	if dateScanned.Valid {
		t := dateScanned.Time.UTC()
		video.DateScanned = &t
	}
}

func assignPlaylistTimes(playlist *Playlist, dateCreated, dateUpdated sql.NullTime) {
	if dateCreated.Valid {
		t := dateCreated.Time.UTC()
		playlist.DateCreated = &t
	}
	if dateUpdated.Valid {
		t := dateUpdated.Time.UTC()
		playlist.DateUpdated = &t
	}
}

func assignPlaylistSummaryTimes(playlist *PlaylistSummary, dateCreated, dateUpdated sql.NullTime) {
	if dateCreated.Valid {
		t := dateCreated.Time.UTC()
		playlist.DateCreated = &t
	}
	if dateUpdated.Valid {
		t := dateUpdated.Time.UTC()
		playlist.DateUpdated = &t
	}
}

func (s *Store) ListRepresentativeVideos() ([]Video, error) {
	rows, err := s.db.Query(`
		SELECT v.id, v.title, v.filename, v.path, v.quality, v.duration, v.tags_json, v.actors_json, v.date_added, v.date_scanned
		FROM videos v
		INNER JOIN (
			SELECT title, MIN(
				CASE quality
					WHEN '4K' THEN 1
					WHEN '2160p' THEN 1
					WHEN '1080p' THEN 2
					WHEN '720p' THEN 3
					WHEN '480p' THEN 4
					ELSE 5
				END
			) as quality_rank
			FROM videos
			GROUP BY title
		) best ON v.title = best.title AND 
			CASE v.quality
				WHEN '4K' THEN 1
				WHEN '2160p' THEN 1
				WHEN '1080p' THEN 2
				WHEN '720p' THEN 3
				WHEN '480p' THEN 4
				ELSE 5
			END = best.quality_rank
		GROUP BY v.title
		ORDER BY v.date_added DESC, v.id DESC`)
	if err != nil {
		return nil, fmt.Errorf("query representative videos: %w", err)
	}
	defer rows.Close()

	var videos []Video
	for rows.Next() {
		video, err := scanVideoSummary(rows)
		if err != nil {
			return nil, fmt.Errorf("scan representative video: %w", err)
		}
		videos = append(videos, video)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate representative videos: %w", err)
	}

	return videos, nil
}

func (s *Store) GetVideoForThumbnail(title string) (Video, error) {
	row := s.db.QueryRow(`
		SELECT id, title, filename, path, quality, duration, tags_json, actors_json, date_added, date_scanned
		FROM videos
		WHERE title = ?
		ORDER BY
			CASE quality
				WHEN '4K' THEN 1
				WHEN '2160p' THEN 1
				WHEN '1080p' THEN 2
				WHEN '720p' THEN 3
				WHEN '480p' THEN 4
				ELSE 5
			END,
			id DESC
		LIMIT 1`, title)

	video, err := scanVideoDetail(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Video{}, err
		}
		return Video{}, fmt.Errorf("get video for thumbnail: %w", err)
	}

	return video, nil
}

func (s *Store) GetVideoForScrubber(title string) (Video, error) {
	row := s.db.QueryRow(`
		SELECT id, title, filename, path, quality, duration, tags_json, actors_json, date_added, date_scanned
		FROM videos
		WHERE title = ?
		ORDER BY
			CASE quality
				WHEN '480p' THEN 1
				WHEN '720p' THEN 2
				WHEN '1080p' THEN 3
				WHEN '2160p' THEN 4
				WHEN '4K' THEN 4
				ELSE 5
			END,
			id DESC
		LIMIT 1`, title)

	video, err := scanVideoDetail(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Video{}, err
		}
		return Video{}, fmt.Errorf("get video for scrubber: %w", err)
	}

	return video, nil
}

func (s *Store) GetVideoForPreview(title string) (Video, error) {
	return s.GetVideoForThumbnail(title)
}

func (s *Store) ListAllTitles() ([]string, error) {
	rows, err := s.db.Query(`SELECT DISTINCT title FROM videos ORDER BY title`)
	if err != nil {
		return nil, fmt.Errorf("query titles: %w", err)
	}
	defer rows.Close()

	var titles []string
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, fmt.Errorf("scan title: %w", err)
		}
		titles = append(titles, title)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate titles: %w", err)
	}

	return titles, nil
}

func (s *Store) ListVideoGroups() ([]VideoGroup, error) {
	rows, err := s.db.Query(`
		SELECT id, title, filename, quality, duration, tags_json, actors_json, date_added, date_scanned
		FROM videos
		ORDER BY title,
			CASE quality
				WHEN '4K' THEN 1
				WHEN '2160p' THEN 1
				WHEN '1080p' THEN 2
				WHEN '720p' THEN 3
				WHEN '480p' THEN 4
				ELSE 5
			END,
			id DESC`)
	if err != nil {
		return nil, fmt.Errorf("query videos: %w", err)
	}
	defer rows.Close()

	var groups []VideoGroup
	var current *VideoGroup

	for rows.Next() {
		var video Video
		var dateAdded sql.NullTime
		var dateScanned sql.NullTime
		var quality sql.NullString
		var tagsJSON string
		var actorsJSON string

		if err := rows.Scan(&video.ID, &video.Title, &video.Filename, &quality, &video.Duration, &tagsJSON, &actorsJSON, &dateAdded, &dateScanned); err != nil {
			return nil, fmt.Errorf("scan video: %w", err)
		}

		assignVideoTimes(&video, dateAdded, dateScanned)
		if quality.Valid {
			video.Quality = quality.String
		}
		video.Tags = parseStringList(tagsJSON)
		video.Actors = parseStringList(actorsJSON)

		if current == nil || current.Title != video.Title {
			groups = append(groups, VideoGroup{
				ID:          video.ID,
				Title:       video.Title,
				Duration:    video.Duration,
				DateAdded:   video.DateAdded,
				DateScanned: video.DateScanned,
				Tags:        append([]string(nil), video.Tags...),
				Actors:      append([]string(nil), video.Actors...),
				Variants:    []VideoVariant{},
			})
			current = &groups[len(groups)-1]
		} else {
			mergeGroupMetadata(current, video)
		}

		qualityStr := video.Quality
		if qualityStr == "" {
			qualityStr = "Original"
		}

		current.Variants = append(current.Variants, VideoVariant{
			ID:       video.ID,
			Quality:  qualityStr,
			Filename: video.Filename,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate videos: %w", err)
	}

	return groups, nil
}

func (s *Store) GetVideoGroupByID(id int64) (VideoGroup, error) {
	var title string
	if err := s.db.QueryRow(`SELECT title FROM videos WHERE id = ?`, id).Scan(&title); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return VideoGroup{}, err
		}
		return VideoGroup{}, fmt.Errorf("get video title by id: %w", err)
	}

	rows, err := s.db.Query(`
		SELECT id, title, filename, quality, duration, tags_json, actors_json, date_added, date_scanned
		FROM videos
		WHERE title = ?
		ORDER BY
			CASE quality
				WHEN '4K' THEN 1
				WHEN '2160p' THEN 1
				WHEN '1080p' THEN 2
				WHEN '720p' THEN 3
				WHEN '480p' THEN 4
				ELSE 5
			END,
			id DESC`, title)
	if err != nil {
		return VideoGroup{}, fmt.Errorf("query video group: %w", err)
	}
	defer rows.Close()

	var group VideoGroup
	initialized := false
	for rows.Next() {
		var video Video
		var dateAdded sql.NullTime
		var dateScanned sql.NullTime
		var quality sql.NullString
		var tagsJSON string
		var actorsJSON string

		if err := rows.Scan(&video.ID, &video.Title, &video.Filename, &quality, &video.Duration, &tagsJSON, &actorsJSON, &dateAdded, &dateScanned); err != nil {
			return VideoGroup{}, fmt.Errorf("scan video group row: %w", err)
		}

		assignVideoTimes(&video, dateAdded, dateScanned)
		if quality.Valid {
			video.Quality = quality.String
		}
		video.Tags = parseStringList(tagsJSON)
		video.Actors = parseStringList(actorsJSON)

		if !initialized {
			group = VideoGroup{
				ID:          video.ID,
				Title:       video.Title,
				Duration:    video.Duration,
				DateAdded:   video.DateAdded,
				DateScanned: video.DateScanned,
				Tags:        append([]string(nil), video.Tags...),
				Actors:      append([]string(nil), video.Actors...),
				Variants:    []VideoVariant{},
			}
			initialized = true
		} else {
			mergeGroupMetadata(&group, video)
		}

		qualityStr := video.Quality
		if qualityStr == "" {
			qualityStr = "Original"
		}

		group.Variants = append(group.Variants, VideoVariant{
			ID:       video.ID,
			Quality:  qualityStr,
			Filename: video.Filename,
		})
	}

	if err := rows.Err(); err != nil {
		return VideoGroup{}, fmt.Errorf("iterate video group: %w", err)
	}
	if !initialized {
		return VideoGroup{}, sql.ErrNoRows
	}

	return group, nil
}

func parseStringList(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return []string{}
	}

	var values []string
	if err := json.Unmarshal([]byte(raw), &values); err != nil {
		return []string{}
	}

	return sanitizeStringList(values)
}

func parseTorrentIndexers(raw string) ([]TorrentIndexer, error) {
	if strings.TrimSpace(raw) == "" {
		return []TorrentIndexer{}, nil
	}

	var indexers []TorrentIndexer
	if err := json.Unmarshal([]byte(raw), &indexers); err != nil {
		return nil, fmt.Errorf("decode torrent indexers: %w", err)
	}

	sanitized := make([]TorrentIndexer, 0, len(indexers))
	seen := make(map[string]struct{}, len(indexers))
	for _, indexer := range indexers {
		cleaned := sanitizeTorrentIndexer(indexer)
		if cleaned.ID == "" || cleaned.TorznabURL == "" || cleaned.APIKey == "" {
			continue
		}
		if _, exists := seen[cleaned.ID]; exists {
			continue
		}
		seen[cleaned.ID] = struct{}{}
		sanitized = append(sanitized, cleaned)
	}

	return sanitized, nil
}

func marshalTorrentIndexers(indexers []TorrentIndexer) (string, error) {
	sanitized := make([]TorrentIndexer, 0, len(indexers))
	seen := make(map[string]struct{}, len(indexers))
	for _, indexer := range indexers {
		cleaned := sanitizeTorrentIndexer(indexer)
		if cleaned.ID == "" || cleaned.TorznabURL == "" || cleaned.APIKey == "" {
			continue
		}
		if _, exists := seen[cleaned.ID]; exists {
			continue
		}
		seen[cleaned.ID] = struct{}{}
		sanitized = append(sanitized, cleaned)
	}

	data, err := json.Marshal(sanitized)
	if err != nil {
		return "", fmt.Errorf("encode torrent indexers: %w", err)
	}
	return string(data), nil
}

func sanitizeTorrentIndexer(indexer TorrentIndexer) TorrentIndexer {
	indexer.ID = strings.TrimSpace(indexer.ID)
	indexer.Label = strings.TrimSpace(indexer.Label)
	indexer.TorznabURL = strings.TrimSpace(indexer.TorznabURL)
	indexer.APIKey = strings.TrimSpace(indexer.APIKey)
	indexer.Tracker = strings.TrimSpace(indexer.Tracker)
	return indexer
}

func marshalStringList(values []string) (string, error) {
	data, err := json.Marshal(sanitizeStringList(values))
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func sanitizeStringList(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	cleaned := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		key := strings.ToLower(trimmed)
		if _, exists := seen[key]; exists {
			continue
		}
		seen[key] = struct{}{}
		cleaned = append(cleaned, trimmed)
	}
	return cleaned
}

func uniqueInt64s(values []int64) []int64 {
	seen := make(map[int64]struct{}, len(values))
	unique := make([]int64, 0, len(values))
	for _, value := range values {
		if _, exists := seen[value]; exists {
			continue
		}
		seen[value] = struct{}{}
		unique = append(unique, value)
	}
	return unique
}

func applyStringListChanges(existing []string, add []string, remove []string) []string {
	result := sanitizeStringList(existing)
	if len(add) > 0 {
		result = sanitizeStringList(append(result, add...))
	}
	if len(remove) == 0 {
		return result
	}

	removeSet := make(map[string]struct{}, len(remove))
	for _, value := range remove {
		removeSet[strings.ToLower(strings.TrimSpace(value))] = struct{}{}
	}

	filtered := make([]string, 0, len(result))
	for _, value := range result {
		if _, shouldRemove := removeSet[strings.ToLower(value)]; shouldRemove {
			continue
		}
		filtered = append(filtered, value)
	}
	return filtered
}

func collectCaseInsensitiveStrings(dst map[string]string, values []string) {
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		key := strings.ToLower(trimmed)
		if _, exists := dst[key]; !exists {
			dst[key] = trimmed
		}
	}
}

func sortedStringMapValues(values map[string]string) []string {
	result := make([]string, 0, len(values))
	for _, value := range values {
		result = append(result, value)
	}
	sort.Slice(result, func(i, j int) bool {
		return strings.ToLower(result[i]) < strings.ToLower(result[j])
	})
	return result
}

func (s *Store) getMetadataCatalogTx(tx *sql.Tx) ([]string, []string, error) {
	tagsValue, err := getOptionalSettingTx(tx, metadataTagsCatalogSettingKey)
	if err != nil {
		return nil, nil, fmt.Errorf("get metadata tags catalog in tx: %w", err)
	}
	actorsValue, err := getOptionalSettingTx(tx, metadataActorsCatalogSettingKey)
	if err != nil {
		return nil, nil, fmt.Errorf("get metadata actors catalog in tx: %w", err)
	}

	return parseStringList(tagsValue), parseStringList(actorsValue), nil
}

func (s *Store) setMetadataCatalogTx(tx *sql.Tx, tags []string, actors []string) error {
	tagsJSON, err := marshalStringList(tags)
	if err != nil {
		return fmt.Errorf("encode metadata tags catalog: %w", err)
	}
	actorsJSON, err := marshalStringList(actors)
	if err != nil {
		return fmt.Errorf("encode metadata actors catalog: %w", err)
	}

	if err := setSettingTx(tx, metadataTagsCatalogSettingKey, tagsJSON); err != nil {
		return fmt.Errorf("save metadata tags catalog: %w", err)
	}
	if err := setSettingTx(tx, metadataActorsCatalogSettingKey, actorsJSON); err != nil {
		return fmt.Errorf("save metadata actors catalog: %w", err)
	}

	return nil
}

func removeMetadataValuesFromAllVideosTx(tx *sql.Tx, removeTags []string, removeActors []string) error {
	rows, err := tx.Query(`SELECT id, tags_json, actors_json FROM videos`)
	if err != nil {
		return fmt.Errorf("query videos for metadata catalog cleanup: %w", err)
	}
	defer rows.Close()

	type metadataRow struct {
		id         int64
		tagsJSON   string
		actorsJSON string
	}

	var updates []metadataRow
	for rows.Next() {
		var row metadataRow
		if err := rows.Scan(&row.id, &row.tagsJSON, &row.actorsJSON); err != nil {
			return fmt.Errorf("scan metadata cleanup row: %w", err)
		}
		updates = append(updates, row)
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate metadata cleanup rows: %w", err)
	}

	for _, row := range updates {
		nextTags := applyStringListChanges(parseStringList(row.tagsJSON), nil, removeTags)
		nextActors := applyStringListChanges(parseStringList(row.actorsJSON), nil, removeActors)

		tagsJSON, err := marshalStringList(nextTags)
		if err != nil {
			return fmt.Errorf("encode cleaned tags: %w", err)
		}
		actorsJSON, err := marshalStringList(nextActors)
		if err != nil {
			return fmt.Errorf("encode cleaned actors: %w", err)
		}

		if _, err := tx.Exec(`UPDATE videos SET tags_json = ?, actors_json = ? WHERE id = ?`, tagsJSON, actorsJSON, row.id); err != nil {
			return fmt.Errorf("update cleaned video metadata: %w", err)
		}
	}

	return nil
}

func getOptionalSettingTx(tx *sql.Tx, key string) (string, error) {
	var value string
	err := tx.QueryRow(`SELECT value FROM settings WHERE key = ?`, key).Scan(&value)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return "", nil
		}
		return "", err
	}
	return value, nil
}

func setSettingTx(tx *sql.Tx, key string, value string) error {
	_, err := tx.Exec(`
		INSERT INTO settings (key, value)
		VALUES (?, ?)
		ON CONFLICT(key) DO UPDATE SET value = excluded.value`, key, value)
	return err
}

func (s *Store) getTitlesForVideoIDs(ids []int64) ([]string, error) {
	placeholders := make([]string, 0, len(ids))
	args := make([]any, 0, len(ids))
	for _, id := range ids {
		placeholders = append(placeholders, "?")
		args = append(args, id)
	}

	rows, err := s.db.Query(`SELECT DISTINCT title FROM videos WHERE id IN (`+strings.Join(placeholders, ",")+`) ORDER BY title`, args...)
	if err != nil {
		return nil, fmt.Errorf("query titles for bulk metadata update: %w", err)
	}
	defer rows.Close()

	var titles []string
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, fmt.Errorf("scan bulk metadata title: %w", err)
		}
		titles = append(titles, title)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate bulk metadata titles: %w", err)
	}

	return titles, nil
}

func loadMetadataForTitle(queryer interface {
	QueryRow(query string, args ...any) *sql.Row
}, title string) ([]string, []string, error) {
	var tagsJSON string
	var actorsJSON string
	if err := queryer.QueryRow(`
		SELECT tags_json, actors_json
		FROM videos
		WHERE title = ?
		ORDER BY id DESC
		LIMIT 1`, title).Scan(&tagsJSON, &actorsJSON); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil, err
		}
		return nil, nil, fmt.Errorf("load video group metadata for title: %w", err)
	}

	return parseStringList(tagsJSON), parseStringList(actorsJSON), nil
}

func (s *Store) getMetadataByTitle(title string) (string, string, error) {
	var tagsJSON string
	var actorsJSON string
	err := s.db.QueryRow(`
		SELECT tags_json, actors_json
		FROM videos
		WHERE title = ? AND (tags_json != '[]' OR actors_json != '[]')
		ORDER BY id DESC
		LIMIT 1`, title).Scan(&tagsJSON, &actorsJSON)
	if err != nil {
		return "", "", err
	}
	return tagsJSON, actorsJSON, nil
}

func mergeGroupMetadata(group *VideoGroup, video Video) {
	group.Tags = sanitizeStringList(append(group.Tags, video.Tags...))
	group.Actors = sanitizeStringList(append(group.Actors, video.Actors...))
}

func (s *Store) GetVideoGroupByTitle(title string) (VideoGroup, error) {
	var id int64
	if err := s.db.QueryRow(`SELECT id FROM videos WHERE title = ? ORDER BY id DESC LIMIT 1`, title).Scan(&id); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return VideoGroup{}, err
		}
		return VideoGroup{}, fmt.Errorf("get video id by title: %w", err)
	}

	return s.GetVideoGroupByID(id)
}

func (s *Store) listPlaylistItems(playlistID int64) ([]VideoGroup, error) {
	titles, err := s.getPlaylistTitles(playlistID)
	if err != nil {
		return nil, err
	}

	items := make([]VideoGroup, 0, len(titles))
	for _, title := range titles {
		group, err := s.GetVideoGroupByTitle(title)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return nil, fmt.Errorf("load playlist item by title: %w", err)
		}
		items = append(items, group)
	}

	return items, nil
}

func (s *Store) getPlaylistTitles(playlistID int64) ([]string, error) {
	if _, err := s.GetPlaylistByIDMeta(playlistID); err != nil {
		return nil, err
	}

	rows, err := s.db.Query(`
		SELECT video_title
		FROM playlist_items
		WHERE playlist_id = ?
		ORDER BY position, video_title`, playlistID)
	if err != nil {
		return nil, fmt.Errorf("query playlist titles: %w", err)
	}
	defer rows.Close()

	titles := make([]string, 0)
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, fmt.Errorf("scan playlist title: %w", err)
		}
		titles = append(titles, title)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate playlist titles: %w", err)
	}

	return titles, nil
}

func (s *Store) GetPlaylistByIDMeta(id int64) (PlaylistSummary, error) {
	if err := s.pruneStalePlaylistItemsForPlaylist(id); err != nil && !errors.Is(err, sql.ErrNoRows) {
		return PlaylistSummary{}, err
	}

	return s.GetPlaylistByIDMetaWithoutPrune(id)
}

func (s *Store) getTitleForVideoID(id int64) (string, error) {
	var title string
	if err := s.db.QueryRow(`SELECT title FROM videos WHERE id = ?`, id).Scan(&title); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return "", err
		}
		return "", fmt.Errorf("get title for video id: %w", err)
	}
	return title, nil
}

func (s *Store) getTitlesForVideoIDsOrdered(ids []int64) ([]string, error) {
	uniqueIDs := uniqueInt64s(ids)
	titles := make([]string, 0, len(uniqueIDs))
	for _, id := range uniqueIDs {
		title, err := s.getTitleForVideoID(id)
		if err != nil {
			return nil, err
		}
		titles = append(titles, title)
	}
	return uniqueStringsPreserveOrder(titles), nil
}

func (s *Store) replacePlaylistTitles(id int64, titles []string) error {
	if _, err := s.GetPlaylistByIDMeta(id); err != nil {
		return err
	}

	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("begin replace playlist items: %w", err)
	}

	if err := setPlaylistTitlesTx(tx, id, titles); err != nil {
		_ = tx.Rollback()
		return err
	}

	if _, err := tx.Exec(`UPDATE playlists SET date_updated = CURRENT_TIMESTAMP WHERE id = ?`, id); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("touch playlist updated time: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit replace playlist items: %w", err)
	}

	return nil
}

func setPlaylistTitlesTx(tx *sql.Tx, playlistID int64, titles []string) error {
	titles = uniqueStringsPreserveOrder(titles)
	if _, err := tx.Exec(`DELETE FROM playlist_items WHERE playlist_id = ?`, playlistID); err != nil {
		return fmt.Errorf("clear playlist items: %w", err)
	}

	for idx, title := range titles {
		if _, err := tx.Exec(`INSERT INTO playlist_items (playlist_id, video_title, position) VALUES (?, ?, ?)`, playlistID, title, idx); err != nil {
			return fmt.Errorf("insert playlist item: %w", err)
		}
	}

	return nil
}

func uniqueStringsPreserveOrder(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	unique := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		key := strings.ToLower(trimmed)
		if _, exists := seen[key]; exists {
			continue
		}
		seen[key] = struct{}{}
		unique = append(unique, trimmed)
	}
	return unique
}

func (s *Store) pruneStalePlaylistItems() error {
	if _, err := s.db.Exec(`
		DELETE FROM playlist_items
		WHERE NOT EXISTS (
			SELECT 1
			FROM videos
			WHERE videos.title = playlist_items.video_title
		)`); err != nil {
		return fmt.Errorf("prune stale playlist items: %w", err)
	}

	return nil
}

func (s *Store) pruneStalePlaylistItemsForPlaylist(playlistID int64) error {
	if _, err := s.GetPlaylistByIDMetaWithoutPrune(playlistID); err != nil {
		return err
	}

	if _, err := s.db.Exec(`
		DELETE FROM playlist_items
		WHERE playlist_id = ?
		  AND NOT EXISTS (
			SELECT 1
			FROM videos
			WHERE videos.title = playlist_items.video_title
		)`, playlistID); err != nil {
		return fmt.Errorf("prune stale playlist items for playlist: %w", err)
	}

	return nil
}

func (s *Store) GetPlaylistByIDMetaWithoutPrune(id int64) (PlaylistSummary, error) {
	var playlist PlaylistSummary
	var dateCreated sql.NullTime
	var dateUpdated sql.NullTime
	err := s.db.QueryRow(`
		SELECT p.id, p.name, p.description, COUNT(vt.title), p.date_created, p.date_updated
		FROM playlists p
		LEFT JOIN playlist_items pi ON pi.playlist_id = p.id
		LEFT JOIN (SELECT DISTINCT title FROM videos) vt ON vt.title = pi.video_title
		WHERE p.id = ?
		GROUP BY p.id, p.name, p.description, p.date_created, p.date_updated`, id).Scan(&playlist.ID, &playlist.Name, &playlist.Description, &playlist.ItemCount, &dateCreated, &dateUpdated)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return PlaylistSummary{}, err
		}
		return PlaylistSummary{}, fmt.Errorf("get playlist meta: %w", err)
	}
	assignPlaylistSummaryTimes(&playlist, dateCreated, dateUpdated)
	return playlist, nil
}

func (s *Store) AddTorrentDownloadHistory(item TorrentDownloadHistory) error {
	_, err := s.db.Exec(`
		INSERT INTO torrent_download_history (title, url, download_url, tracker, size, seeders, leechers, freeleech, status, downloaded_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		item.Title, item.URL, item.DownloadURL, item.Tracker, item.Size, item.Seeders, item.Leechers, item.Freeleech, item.Status, item.DownloadedAt)
	if err != nil {
		return fmt.Errorf("add torrent download history: %w", err)
	}
	return nil
}

func (s *Store) ListTorrentDownloadHistory(page, perPage int) ([]TorrentDownloadHistory, int, error) {
	return s.ListTorrentDownloadHistoryFiltered("", "", page, perPage)
}

func (s *Store) ClearTorrentDownloadHistory() error {
	_, err := s.db.Exec(`DELETE FROM torrent_download_history`)
	if err != nil {
		return fmt.Errorf("clear torrent download history: %w", err)
	}
	return nil
}

func (s *Store) migrateTorrentHistoryStatus() error {
	var count int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM pragma_table_info('torrent_download_history') WHERE name = 'status'`).Scan(&count)
	if err != nil {
		return fmt.Errorf("check torrent history status column: %w", err)
	}
	if count == 0 {
		_, err := s.db.Exec(`ALTER TABLE torrent_download_history ADD COLUMN status TEXT NOT NULL DEFAULT 'pending'`)
		if err != nil {
			return fmt.Errorf("add status column to torrent history: %w", err)
		}
		if s.logger != nil {
			s.logger.Info("migrated torrent history table", "added_column", "status")
		}
	}
	return nil
}

func (s *Store) migrateUserForcePasswordChange() error {
	var count int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM pragma_table_info('users') WHERE name = 'force_password_change'`).Scan(&count)
	if err != nil {
		return fmt.Errorf("check users force_password_change column: %w", err)
	}
	if count == 0 {
		_, err := s.db.Exec(`ALTER TABLE users ADD COLUMN force_password_change INTEGER NOT NULL DEFAULT 0`)
		if err != nil {
			return fmt.Errorf("add force_password_change column to users: %w", err)
		}
		if s.logger != nil {
			s.logger.Info("migrated users table", "added_column", "force_password_change")
		}
	}
	return nil
}

func (s *Store) DeleteTorrentDownloadHistory(id int64) error {
	result, err := s.db.Exec(`DELETE FROM torrent_download_history WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("delete torrent download history: %w", err)
	}
	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("check deleted rows: %w", err)
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (s *Store) ListTorrentDownloadHistoryFiltered(tracker, search string, page, perPage int) ([]TorrentDownloadHistory, int, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	if perPage > 100 {
		perPage = 100
	}

	whereClause := "1=1"
	args := []any{}

	if tracker != "" {
		whereClause += " AND tracker = ?"
		args = append(args, tracker)
	}
	if search != "" {
		whereClause += " AND title LIKE ?"
		args = append(args, "%"+search+"%")
	}

	countQuery := `SELECT COUNT(*) FROM torrent_download_history WHERE ` + whereClause
	var totalCount int
	err := s.db.QueryRow(countQuery, args...).Scan(&totalCount)
	if err != nil {
		return nil, 0, fmt.Errorf("count filtered torrent history: %w", err)
	}

	queryArgs := append([]any{}, args...)
	offset := (page - 1) * perPage
	queryArgs = append(queryArgs, perPage, offset)

	rows, err := s.db.Query(`
		SELECT id, title, url, download_url, tracker, size, seeders, leechers, freeleech, status, downloaded_at
		FROM torrent_download_history
		WHERE `+whereClause+`
		ORDER BY downloaded_at DESC
		LIMIT ? OFFSET ?`, queryArgs...)
	if err != nil {
		return nil, 0, fmt.Errorf("query filtered torrent history: %w", err)
	}
	defer rows.Close()

	var items []TorrentDownloadHistory
	for rows.Next() {
		var item TorrentDownloadHistory
		var downloadedAt sql.NullTime
		err := rows.Scan(&item.ID, &item.Title, &item.URL, &item.DownloadURL, &item.Tracker, &item.Size, &item.Seeders, &item.Leechers, &item.Freeleech, &item.Status, &downloadedAt)
		if err != nil {
			return nil, 0, fmt.Errorf("scan torrent history: %w", err)
		}
		if downloadedAt.Valid {
			item.DownloadedAt = &downloadedAt.Time
		}
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("iterate torrent history: %w", err)
	}

	return items, totalCount, nil
}
