package main

import "time"

type Video struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Filename    string     `json:"filename"`
	Path        string     `json:"-"`
	Quality     string     `json:"quality,omitempty"`
	Duration    int        `json:"duration"`
	DateAdded   *time.Time `json:"date_added,omitempty"`
	DateScanned *time.Time `json:"date_scanned,omitempty"`
	Tags        []string   `json:"tags,omitempty"`
	Actors      []string   `json:"actors,omitempty"`
}

type VideoVariant struct {
	ID       int64  `json:"id"`
	Quality  string `json:"quality"`
	Filename string `json:"filename"`
}

type VideoGroup struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Duration    int            `json:"duration"`
	DateAdded   *time.Time     `json:"date_added,omitempty"`
	DateScanned *time.Time     `json:"date_scanned,omitempty"`
	Tags        []string       `json:"tags,omitempty"`
	Actors      []string       `json:"actors,omitempty"`
	Variants    []VideoVariant `json:"variants"`
}

type ScannedVideo struct {
	Title    string
	Filename string
	Path     string
	Duration int
	Quality  string
}

type ScanReport struct {
	FilesFound int `json:"files_found"`
	Inserted   int `json:"inserted"`
	Updated    int `json:"updated"`
	Skipped    int `json:"skipped"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"-"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

type DirectoryEntry struct {
	Name        string `json:"name"`
	Path        string `json:"path"`
	IsDirectory bool   `json:"isDirectory"`
	Size        int64  `json:"size,omitempty"`
}

type MediaPathRequest struct {
	Path string `json:"path"`
}

type MediaPathResponse struct {
	Path string `json:"path"`
}

type ClearDatabaseResponse struct {
	Status string `json:"status"`
}

type PreviewSpriteResponse struct {
	SpriteURL   string    `json:"sprite_url"`
	FrameWidth  int       `json:"frame_width"`
	FrameHeight int       `json:"frame_height"`
	Columns     int       `json:"columns"`
	Rows        int       `json:"rows"`
	Timestamps  []float64 `json:"timestamps"`
	Duration    int       `json:"duration"`
	SampleCount int       `json:"sample_count"`
}

type GenerationSettingsResponse struct {
	GenerateThumbnails      bool `json:"generate_thumbnails"`
	GenerateScrubberSprites bool `json:"generate_scrubber_sprites"`
	GenerateHoverPreviews   bool `json:"generate_hover_previews"`
	AutoGenerateDuringScan  bool `json:"auto_generate_during_scan"`
}

type GenerationSettingsRequest struct {
	GenerateThumbnails      bool `json:"generate_thumbnails"`
	GenerateScrubberSprites bool `json:"generate_scrubber_sprites"`
	GenerateHoverPreviews   bool `json:"generate_hover_previews"`
	AutoGenerateDuringScan  bool `json:"auto_generate_during_scan"`
}

type PreviewGenerationRequest struct {
	GenerateThumbnails      bool `json:"generate_thumbnails"`
	GenerateScrubberSprites bool `json:"generate_scrubber_sprites"`
	GenerateHoverPreviews   bool `json:"generate_hover_previews"`
}

type VideoMetadataUpdateRequest struct {
	Tags   []string `json:"tags"`
	Actors []string `json:"actors"`
}

type BulkVideoMetadataUpdateRequest struct {
	IDs          []int64  `json:"ids"`
	AddTags      []string `json:"add_tags"`
	RemoveTags   []string `json:"remove_tags"`
	AddActors    []string `json:"add_actors"`
	RemoveActors []string `json:"remove_actors"`
}

type VideoMetadataOptionsResponse struct {
	Tags   []string `json:"tags"`
	Actors []string `json:"actors"`
}

type SettingsMetadataUpdateRequest struct {
	AddTags      []string `json:"add_tags"`
	RemoveTags   []string `json:"remove_tags"`
	AddActors    []string `json:"add_actors"`
	RemoveActors []string `json:"remove_actors"`
}

type TorrentIndexer struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	TorznabURL string `json:"torznab_url"`
	APIKey     string `json:"api_key"`
	Tracker    string `json:"tracker"`
}

type TorrentIndexerCreateRequest struct {
	Label      string `json:"label"`
	TorznabURL string `json:"torznab_url"`
	APIKey     string `json:"api_key"`
}

type TorrentIndexerResponse struct {
	ID           string `json:"id"`
	Label        string `json:"label"`
	TorznabURL   string `json:"torznab_url"`
	Tracker      string `json:"tracker"`
	MaskedAPIKey string `json:"masked_api_key"`
}

type TorrentSearchResult struct {
	Title       string     `json:"title"`
	URL         string     `json:"url"`
	DownloadURL string     `json:"download_url"`
	Tracker     string     `json:"tracker"`
	Size        int64      `json:"size"`
	Seeders     int        `json:"seeders"`
	Leechers    int        `json:"leechers"`
	Freeleech   bool       `json:"freeleech"`
	Published   *time.Time `json:"published,omitempty"`
}

type TorrentSearchResponse struct {
	Query    string                `json:"query"`
	Results  []TorrentSearchResult `json:"results"`
	Warnings []string              `json:"warnings,omitempty"`
}

type TorrentDownloadHistory struct {
	ID           int64      `json:"id"`
	Title        string     `json:"title"`
	URL          string     `json:"url"`
	DownloadURL  string     `json:"download_url"`
	Tracker      string     `json:"tracker"`
	Size         int64      `json:"size"`
	Seeders      int        `json:"seeders"`
	Leechers     int        `json:"leechers"`
	Freeleech    bool       `json:"freeleech"`
	Status       string     `json:"status"`
	DownloadedAt *time.Time `json:"downloaded_at"`
}

type TorrentHistoryFilterRequest struct {
	Tracker string `json:"tracker"`
	Search  string `json:"search"`
	Page    int    `json:"page"`
	PerPage int    `json:"per_page"`
}

type TorrentHistoryResponse struct {
	Items       []TorrentDownloadHistory `json:"items"`
	TotalCount  int                      `json:"total_count"`
	CurrentPage int                      `json:"current_page"`
	TotalPages  int                      `json:"total_pages"`
}

type BulkVideoMetadataUpdateResponse struct {
	UpdatedCount  int          `json:"updated_count"`
	UpdatedGroups []VideoGroup `json:"updated_groups"`
}

type PreviewGenerationStatus struct {
	Status                  string     `json:"status"`
	Source                  string     `json:"source,omitempty"`
	Running                 bool       `json:"running"`
	GenerateThumbnails      bool       `json:"generate_thumbnails"`
	GenerateScrubberSprites bool       `json:"generate_scrubber_sprites"`
	GenerateHoverPreviews   bool       `json:"generate_hover_previews"`
	TotalVideos             int        `json:"total_videos"`
	ProcessedVideos         int        `json:"processed_videos"`
	CurrentVideoID          int64      `json:"current_video_id,omitempty"`
	CurrentVideoTitle       string     `json:"current_video_title,omitempty"`
	CurrentStep             string     `json:"current_step,omitempty"`
	Errors                  int        `json:"errors"`
	Message                 string     `json:"message,omitempty"`
	StartedAt               *time.Time `json:"started_at,omitempty"`
	CompletedAt             *time.Time `json:"completed_at,omitempty"`
}

type PlaylistSummary struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description,omitempty"`
	ItemCount   int        `json:"item_count"`
	DateCreated *time.Time `json:"date_created,omitempty"`
	DateUpdated *time.Time `json:"date_updated,omitempty"`
}

type Playlist struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description,omitempty"`
	Items       []VideoGroup `json:"items"`
	DateCreated *time.Time   `json:"date_created,omitempty"`
	DateUpdated *time.Time   `json:"date_updated,omitempty"`
}

type PlaylistCreateRequest struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	VideoIDs    []int64 `json:"video_ids"`
}

type PlaylistUpdateRequest struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type PlaylistItemsRequest struct {
	VideoIDs []int64 `json:"video_ids"`
}

type errorResponse struct {
	Error string `json:"error"`
}
